apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: otel-disabled
  namespace: dev
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/language: java
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "false"
    app.kubernetes.io/part-of: otel-disabled
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
      - name: BP_OPENTELEMETRY_ENABLED
        value: "false"
  env:
    - name: OTEL_JAVAAGENT_ENABLED
      value: "false"
    - name: OTEL_METRICS_EXPORTER
      value: "false"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: clusterBuilder
    value: default-with-otel
  - name: gitops_ssh_secret
    value: github-ssh-dev
  source:
    git:
      url: ssh://git@github.com/rabeyta/tanzu-java-web-app.git
      ref:
        branch: main
