#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.name + "-pr-" + str(data.values.pr) + "-" + str(data.values.sha)
  namespace: #@ data.values.namespace
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/pull-request: "true"
    app.kubernetes.io/part-of: #@ data.values.name
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  source:
    git:
      url: #@ "https://github.com/" + data.values.repo
      ref:
        branch: #@ data.values.branch