name: TAP PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: install-kubectl
      uses: azure/setup-kubectl@v3
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    - name: Install ytt
      uses: carvel-dev/setup-action@v2.0.0
      with:
        only: ytt
        ytt: v0.47.0
    - name: build workload template
      run: |
        echo -n ${{ vars.WORKLOAD_YAML }} | base64 -d | ytt -f - \
        --data-value-yaml name=tanzu-java-web-app \
        --data-value-yaml namespace=dev \
        --data-value-yaml pr=${{ github.event.pull_request.number }} \
        --data-value-yaml sha=$(git rev-parse --short HEAD) \
        --data-value-yaml branch=${{ github.head_ref }} \
        --data-value-yaml repo=${{ github.repository }} --validate=false | kubectl apply -f-

